### ISSUE TITLE
Question about testing with presser

### ISSUE THREAD

**Issue by maelle** [r-lib/presser#29]
I haven't started using presser at all yet so it might be a stupid question.

In https://r-lib.github.io/presser/articles/introduction.html#writing-apps you write "Use web$url() to query the URL of the app.".

In my packages wrapping web APIs I often have [a function returning the URL](https://github.com/ropensci/ropenaq/blob/6319fcb9c8065b46fc61dcbd0d25745bc8228a02/R/utils.R#L4) of the API, and the user cannot change it.

In tests, would I need to mock this function to return `web$url()` instead? Or maybe the fact that the API URL isn't customizable in my packages is a bad idea.

**Comment by gaborcsardi** [comment]
Yes, a could solution is to support setting the base url via an environment variable. https://r-lib.github.io/presser/articles/how-to.html#how-do-i-make-my-app-connect-to-presser-when-the-tests-are-running
https://r-lib.github.io/presser/articles/how-to.html#how-to-make-sure-that-my-code-works-with-the-real-api

**Comment by maelle** [comment]
Thanks, and I realize I missed the how-tos!!
