### ISSUE TITLE
is this the expected behavior?

### ISSUE THREAD

**Issue by maelle** [r-lib/presser#37]
``` r
app <- presser::new_app()
app$get("/", function(req, res) {
  res$set_status(502L)$send_json(NULL)
})
web <-  presser::new_app_process(app)
httr::status_code(httr::GET(web$url()))
#> [1] 502
web$stop()

app <- presser::new_app()
app$get("/", function(req, res) {
  res$set_status(502L)
})
web <-  presser::new_app_process(app)
httr::status_code(httr::GET(web$url()))
#> [1] 404
web$stop()
```

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by gaborcsardi** [comment]
I guess it would make sense to send an empty response with status code 502, so it is a bug. Pretty easy to work around, though.

**Comment by maelle** [comment]
Yeah I am using a workaround at the moment, the first example in my reprex

**Comment by gaborcsardi** [comment]
Actually, it makes sense that the response is only sent if you call `send*`, and there is also `$send_status()` to send a status code with an empty body. So I don't think I want to change this.

**Comment by maelle** [comment]
Oooh ok I will switch to send_status

**Comment by maelle** [comment]
I changed the code line in my test.

Should this be closed, as it is the expected behavior?
