### ISSUE TITLE
provide a function à la withr::local?

### ISSUE THREAD

**Issue by maelle** [r-lib/presser#42]
So that one would write, instead of

```r
web <-  presser::new_app_process(app)
withr::defer(web$stop())
```

```r
presser::local_app_process(app)
```

?

**Comment by maelle** [comment]
(related to #36)

**Comment by gaborcsardi** [comment]
What exactly would `local_app_process()` do?

**Comment by maelle** [comment]
What the two lines above do i.e. stop the app when the test is over

**Comment by gaborcsardi** [comment]
I don't think people should do this often, because starting a new process for each `test_that()` block is going to be very slow. 

It is better if there is a single web server process for the whole testsuite or for the test file.

So an alternative would be to check if there is a web server already and if not, then start it. But then the `local_app_process()` name is misleading.

**Comment by gaborcsardi** [comment]
Actually, I think we could have a `local_app_process()` function that you could use
* within `test_that()`,
* at the beginning of a test file, or
* in a setup or helper file.

**Comment by gaborcsardi** [comment]
Although maybe that would be misleading because that's not how you are supposed to do file-level and testsuite-level resource management in testthat.

**Comment by maelle** [comment]
But aren't you supposed to do withr::defer these days in tests? So the function would ensure you don't forget to stop the app. Indeed it could be in setup/helper files.

**Comment by gaborcsardi** [comment]
So I wrote this, untested right now. It is quite hard to write it in a way that `local_app_process()` works within `test_that()` and at the beginning of a file, etc.

OTOH, how about just having an `app_process` that starts up if needed. When you call `url()` or `get_port()` on it, it checks if it is running, and if not, then it starts the app process. That way you don't really need to worry about the app process, and how it is started and stopped.
