### ISSUE TITLE
teardown env

### ISSUE THREAD

**Issue by maelle** [r-lib/presser#48]
In the how-to vignette why isn't `testthat::teardown_env()` called right away i.e.

````

```{r eval = FALSE}
httpbin <- local_app_process(httpbin_app(), .local_envir = testthat::teardown_env())
```

If the app process is created in the helper file, then it is ready use after `load_all()`, and (by default) the actual process will be started at the first `$url()` or `$get_port()` call.
You can also start it manually with `$start()`.

Using `.local_envir = testthat::teardown_env())` ensures the process will be stopped after tests are run.

````

**Comment by maelle** [comment]
In the same fragment, reg `You can also start it manually with `$start()`.` Would it be worth to remind the existence of `start = TRUE` at that point?

**Comment by gaborcsardi** [comment]
> In the how-to vignette why isn't testthat::teardown_env() called right away i.e.

where is this exactly?

> In the same fragment, reg You can also start it manually with $start(). Would it be worth to remind the existence of start = TRUE at that point?

it is fine, people should not start it manually, anyway. Better to start on demand.

**Comment by maelle** [comment]
https://github.com/r-lib/presser/blob/7b9890bd26f39b918869cf9abb2d7a43289bc372/vignettes/how-to.Rmd#L57

**Comment by gaborcsardi** [comment]
You cannot call `teardown_env()` in the helper file, because the tests are not running (yet), so there is no teardown env.

**Comment by maelle** [comment]
aaah too bad, now I get it.
