### ISSUE TITLE
add a point to "How do I use presser in my package?"

### ISSUE THREAD

**Issue by maelle** [r-lib/presser#51]
It's linked to "How to make sure that my code works with the real API?" but is something linked to the package code outside of tests. I'd find something like the tip below very helpful.

````markdown
With presser you will spin up fake services and you will want your package to connect to that rather than the real web API.
How to make it as smooth as possible?

Instead of simply hard-coding the URL of web services your code is interacting with, use a function returning it, and make sure you can change the output of that function with an environment variable or option.

E.g.

```r
service_url <- function() {
	if(nzchar(Sys.getenv("SERVICE_URL")) {
		return(Sys.getenv("SERVICE_URL"))
	}
	return("https://service.url")
}

# rest of the package code

foobar <- function() {
	httr::GET(service_url())
}

```

And then in tests you'd set the environment variable `SERVICE_URL` to be the url of the app you are running.

````

**Comment by maelle** [comment]
I see it comes later in "How do I make my app connect to presser when the tests are running?", it'd make sense to at least link this part from the very first part to make it clear that some changes of the package code might be warranted?

**Comment by gaborcsardi** [comment]
> I see it comes later in "How do I make my app connect to presser when the tests are running?", it'd make sense to at least link this part from the very first part to make it clear that some changes of the package code might be warranted?

Right, but this is only needed if you want to use the same tests against the real api and the fake api.

**Comment by gaborcsardi** [comment]
And actually, it is item number 3 in the list, so we would link from number 1 to number 3? I don't think it is really needed?

**Comment by maelle** [comment]
I have made a PR that shuffles subsections and mentions them instead of linking to them.

> Right, but this is only needed if you want to use the same tests against the real api and the fake api.

No in general you need to have a way to connect the code to a different URL? I've added two sentences to my PR to make it explicit that it is only needed if the URL to the service is not an argument of your functions.
