### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/presser#55]
For R developers that are not that familiar with web apps. E.g. app, middleware, etc.

**Comment by maelle** [comment]
and like in vcr docs explain why the package is called this way (until you rename it :-) )?

**Comment by gaborcsardi** [comment]
Should this be a separate article, so it is visible? Or part of the introduction?

**Comment by maelle** [comment]
In the README and intro, and maybe even in the package manual pages? But if I have to chose a single location, the intro.

**Comment by gaborcsardi** [comment]
If you want it at so many places, then why not make it an article and put it in the main menu, and link it from the README?

**Comment by maelle** [comment]
I was thinking an Rmd fragment would help.

Another concept to clarify: app vs process. The app is more of a recipe for an app, or specifications for the app. The fake web service is a _process_ which is a deployment of the app. (my bad phrasing)

**Comment by gaborcsardi** [comment]
> I was thinking an Rmd fragment would help.

Sure, but I think putting it everywhere is too overwhelming, no?

> Another concept to clarify: app vs process. The app is more of a recipe for an app, or specifications for the app. The fake web service is a process which is a deployment of the app. (my bad phrasing)

Well, you can happily start an app without a process, in the current R session. IDK if we need to clarify process, it is just an operating system process.

**Comment by maelle** [comment]
oooh right see why _I_ need the glossary. 

I'll make a PR. I don't think duplicating the content is overwhelming but maybe it is. :thinking:
